/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.peer39.htmlreader;

class AppTestTemp {
   // @Test void appHasAGreeting() {
        Part1 classUnderTest = new Part1();
      //  assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
   // }
}
